### ISSUE TITLE
Cannot login: 400 Bad request

### ISSUE THREAD

**Issue by sraboni** [tlack/snaphax#15]
Hello
I am trying to login using this API. But it returns "400 Bad Request" always.
I have tried from my local machine and our dev server as well. But it always returns the same error.

Please help.
Thanks.

**Comment by hako** [comment]
snaphax has not been updated for over 3 years and Snapchat's API has changed a lot since then. 

Use [SC-API](https://github.com/mgp25/SC-API) instead.

**Comment by sraboni** [comment]
Hello Hako,
Thank you. This API worked.
